config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  require 'sidekiq/web'
  resources :order_admin_attachments
  root 'welcome#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  authenticate :admin_user do 
    mount Sidekiq::Web => '/sidekiq'
  end
  concern :commentable do
    resources :comments, shallow: true
  end
  get 'packages/index'
  resources :profiles, only: [:show, :edit, :update]
  resources :orders, only: [:new, :update, :show, :edit, :destroy], concerns: :commentable do
    collection do
      get :search
      post 'download_photos' => 'welcome#download_photos_as_zip'
    end
    resources :user_attachments, :only => [:create, :destroy] # support #create and #destroy
    resources :admin_attachments
  end
  resources :packages, only: [:index, :show]
  resources :order_items, only: [:destroy]
  resources :comments, only: [:create, :destroy]

  

  

end

app/models/order_admin_attachment.rb
# == Schema Information
#
# Table name: order_admin_attachments
#
#  id                  :integer          not null, primary key
#  order_id            :integer
#  image               :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  image_processing    :boolean          default("false"), not null
#  temporary_image_url :string
#

class OrderAdminAttachment < ActiveRecord::Base
  mount_uploader :image, AdminAttachmentUploader
  # process_in_background :image
  belongs_to :order

  validates :temporary_image_url, presence: true
  
  # attr_accessible :image, :user_id, :original_image_url, :comment
  # mount_uploader :image, ImageUploader

  before_save :check_url
  after_commit :process_async

  scope :recent, -> { order("created_at desc") }

  private

  def check_url
    self.image_processing = true if new_record? && temporary_image_url
  end

  def process_async
    ProcessImageWorker.perform_async(self.id) if temporary_image_url && image_processing
  end
end

app/controllers/order_admin_attachments_controller.rb
class OrderAdminAttachmentsController < InheritedResources::Base

  private

    def order_admin_attachment_params
      params.require(:order_admin_attachment).permit(:order_id, :image)
    end
end

app/helpers/order_admin_attachments_helper.rb
module OrderAdminAttachmentsHelper
end

app/views/order_admin_attachments/_form.html.erb
<%= simple_form_for(@order_admin_attachment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :order_id %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/order_admin_attachments/edit.html.erb
<h1>Editing Order Admin Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_admin_attachment %> |
<%= link_to 'Back', order_admin_attachments_path %>

app/views/order_admin_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Order Admin Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Attachment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_admin_attachments.each do |order_admin_attachment| %>
      <tr>
        <td><%= order_admin_attachment.order_id %></td>
        <td><%= order_admin_attachment.image %></td>
        <td><%= link_to 'Show', order_admin_attachment %></td>
        <td><%= link_to 'Edit', edit_order_admin_attachment_path(order_admin_attachment) %></td>
        <td><%= link_to 'Destroy', order_admin_attachment, method: :delete, data: { confirm: 'Tryk OK for at slette ordren' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order admin attachment', new_order_admin_attachment_path %>

app/views/order_admin_attachments/new.html.erb
<h1>New Order Admin Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', order_admin_attachments_path %>

app/views/order_admin_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order_admin_attachment.order_id %>
</p>

<p>
  <strong>Attachment:</strong>
  <%= @order_admin_attachment.image %>
</p>

<%= link_to 'Edit', edit_order_admin_attachment_path(@order_admin_attachment) %> |
<%= link_to 'Back', order_admin_attachments_path %>