config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  require 'sidekiq/web'
  resources :order_admin_attachments
  root 'welcome#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  authenticate :admin_user do 
    mount Sidekiq::Web => '/sidekiq'
  end
  concern :commentable do
    resources :comments, shallow: true
  end
  get 'packages/index'
  resources :profiles, only: [:show, :edit, :update]
  resources :orders, only: [:new, :update, :show, :edit, :destroy], concerns: :commentable do
    collection do
      get :search
      post 'download_photos' => 'welcome#download_photos_as_zip'
    end
    resources :user_attachments, :only => [:create, :destroy] # support #create and #destroy
    resources :admin_attachments
  end
  resources :packages, only: [:index, :show]
  resources :order_items, only: [:destroy]
  resources :comments, only: [:create, :destroy]

  

  

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag 'logo', height: '23', width: '157' %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li class="<%= params[:controller] == 'welcome' && params[:action] == 'index' ? 'active' : '' %>"><%= link_to "Oversigt", root_path, class: "new-order-link" %></li>
          <li class="<%= params[:controller] == 'packages' && params[:action] == 'index' ? 'active' : '' %>"><%= link_to "Ny bestilling", packages_path, class: "new-order-link" %></li>
        </ul>
      <% end %>
      <% if (params[:controller] == 'welcome' && params[:action] == 'index') || (params[:controller] == 'orders' && (params[:action] == "search" || params[:action] == "show")) %>
        <%= form_tag search_orders_path, :method => 'get', :id => "orders_search", class: "navbar-form navbar-left" do %>
          <%= hidden_field_tag :direction, params[:direction] %>
          <%= hidden_field_tag :sort, params[:sort] %>
          <div class="form-group">
            <%= text_field_tag :q, params[:q], class: 'form-control', placeholder: "Søg i ordrer" %>
          </div>
          <%= submit_tag "Søg", :name => nil, class: 'btn btn-default' %>
        <% end %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Min profil", profile_path(current_user.profile) %></li>
              <li><%= link_to "Rediger", edit_profile_path(current_user.profile) %></li>
              <li><%= link_to "Log ud", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log ind", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>