config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  require 'sidekiq/web'
  resources :order_admin_attachments
  root 'welcome#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  authenticate :admin_user do 
    mount Sidekiq::Web => '/sidekiq'
  end
  concern :commentable do
    resources :comments, shallow: true
  end
  get 'packages/index'
  resources :profiles, only: [:show, :edit, :update]
  resources :orders, only: [:new, :update, :show, :edit, :destroy], concerns: :commentable do
    collection do
      get :search
      post 'download_photos' => 'welcome#download_photos_as_zip'
    end
    resources :user_attachments, :only => [:create, :destroy] # support #create and #destroy
    resources :admin_attachments
  end
  resources :packages, only: [:index, :show]
  resources :order_items, only: [:destroy]
  resources :comments, only: [:create, :destroy]

  

  

end

app/controllers/welcome_controller.rb
require 'open-uri'

class WelcomeController < ApplicationController
   # enable streaming responses
  include ActionController::Streaming
  # enable zipline
  include Zipline

  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction

  def index
    case params[:state]
    when "ordered"
      if params[:q].present?
        @orders = current_user.orders.ordered.search_all(params[:q]).custom_sort(sort_column, sort_direction).page(params[:page]).per(10)
      else
        @orders = current_user.orders.ordered.custom_sort(sort_column, sort_direction).page(params[:page]).per(10)
      end
    when "booked"
      if params[:q].present?
        @orders = current_user.orders.booked.search_all(params[:q]).custom_sort(sort_column, sort_direction).page(params[:page]).per(10)
      else
        @orders = current_user.orders.booked.custom_sort(sort_column, sort_direction).page(params[:page]).per(10)
      end
    when "completed"
      if params[:q].present?
        @orders = current_user.orders.completed.search_all(params[:q]).custom_sort(sort_column, sort_direction).page(params[:page]).per(10)
      else
        @orders = current_user.orders.completed.custom_sort(sort_column, sort_direction).page(params[:page]).per(10)
      end
    else
      if params[:q].present?
        @orders = current_user.orders.ordered.search_all(params[:q]).custom_sort(sort_column, sort_direction).page(params[:page]).per(10)
      else
        @orders = current_user.orders.ordered.custom_sort(sort_column, sort_direction).page(params[:page]).per(10)
      end
    end
  end

  def download_photos_as_zip
    if params[:image_ids].nil? || params[:image_ids].empty?
      redirect_to :back, notice: "Vælg mindst ét billede." 
    else
      file_urls = OrderAdminAttachment.where(id: params[:image_ids]).map{|i| i.image_url}

      file_mappings = file_urls.lazy.map { |url| [open(url), url.split('?')[0].split('/').last] }
      zipline(file_mappings, 'download.zip')
    end
  end
  private

    def sort_column
      Order.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-3 col-md-offset-4 col-lg-offset-4">
  <ul class="nav nav-pills">
    <li role="presentation" class="<%= params[:controller] == 'welcome' && params[:action] == 'index' && (params[:state].nil? || params[:state] == 'ordered') ? 'active' : '' %>"><%= link_to "Bestilte", root_path(state: "ordered", q: params[:q]) %></li>
    <li role="presentation" class="<%= params[:controller] == 'welcome' && params[:action] == 'index' && params[:state] == 'booked' ? 'active' : '' %>"><%= link_to "Bookede", root_path(state: "booked", q: params[:q]) %></li>
    <li role="presentation" class="<%= params[:controller] == 'welcome' && params[:action] == 'index' && params[:state] == 'completed' ? 'active' : '' %>"><%= link_to "Færdige", root_path(state: "completed", q: params[:q]) %></li>
  </ul>
  <br/>
</div>
<% if @orders.present? %>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th><%= sortable "address", "Adresse", "Order" %></th>
          <th><%= sortable "case_number", "Sagsnummer", "Order" %></th>
          <% unless params[:state] == "booked" %>
            <th><%= sortable "updated_at", "Senest opdateret", "Order" %></th>
          <% else %>
            <th><%= sortable "delivery_time", "Booket til", "Order" %></th>
          <% end %>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= order.address %></td>
            <td><%= order.case_number %></td>
            <% unless params[:state] == "booked" %>
            <td><%= order.updated_at.in_time_zone("CET").strftime("%d/%m/%Y %H:%M") %></td>
            <% else %>
              <td><%= order.delivery_time.present? ? order.delivery_time.in_time_zone("CET").strftime("%d/%m/%Y %H:%M") : "-" %></td>
            <% end %>
            <td>
              <%= link_to "Detaljer", order, class: "btn btn-xs btn-primary" %>
              <% if order.ordered? %>
                <%= link_to "Rediger", edit_order_path(order), class: "btn btn-xs btn-info" %>
                <%= link_to "Slet", order, method: :delete, data: {confirm: "Tryk OK for at slette ordren"}, class: "btn btn-xs btn-danger" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate(@orders, theme: 'twitter-bootstrap-3', pagination_class: "pagination-sm", state: params[:state]) %>
  </div>
<% end %>