config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  require 'sidekiq/web'
  resources :order_admin_attachments
  root 'welcome#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  authenticate :admin_user do 
    mount Sidekiq::Web => '/sidekiq'
  end
  concern :commentable do
    resources :comments, shallow: true
  end
  get 'packages/index'
  resources :profiles, only: [:show, :edit, :update]
  resources :orders, only: [:new, :update, :show, :edit, :destroy], concerns: :commentable do
    collection do
      get :search
      post 'download_photos' => 'welcome#download_photos_as_zip'
    end
    resources :user_attachments, :only => [:create, :destroy] # support #create and #destroy
    resources :admin_attachments
  end
  resources :packages, only: [:index, :show]
  resources :order_items, only: [:destroy]
  resources :comments, only: [:create, :destroy]

  

  

end

app/views/admin/all_comments/_preview_button.html.erb
<% custom_style = 'border: none !important;background: none;box-shadow: none;'%>
<div id='title_bar' style="<%=custom_style%>">
  <div class='action_items'>
    <span class='action_item'>
      <a href="<%= preview_path%>" target='_blank' style='width: 100px;text-align: center;'>Write a Comment</a>
    </span>
  </div>
</div>

app/views/admin/all_comments/_write_a_comment_reply.html.erb
<div class="comment-new-reply">
  <div class="comm-bar-holder">
    <% type = comment.commentable_type.downcase%>
    <%= form_for(([comment.commentable, comment.commentable.comments.new]), url: admin_comment_path, html: {class: "row comm-form"}) do |f| %>
      <%= f.text_area :comment, :placeholder => "Add a comment", :class => "form-control" %>
      <%= hidden_field_tag "#{comment.commentable_type.downcase}_id", comment.commentable.id %>
      <%= f.submit "Write a Comment", :class => "basic-red-btn large btn-right ladda-button btn_commt", :title => "Reply to the ." %>
    <% end %>
  </div>
</div>